"""Europe demographics data."""
EUROPE_DEMOGRAPHICS = {
    "countries": ["Germany", "France", "United Kingdom", "Italy", "Spain", "Netherlands"],
    "cities": {
        "London": {"weight": 0.15}, "Paris": {"weight": 0.12}, "Berlin": {"weight": 0.10},
        "Munich": {"weight": 0.06}, "Madrid": {"weight": 0.08}, "Barcelona": {"weight": 0.06},
        "Rome": {"weight": 0.07}, "Milan": {"weight": 0.06}, "Amsterdam": {"weight": 0.06},
        "Hamburg": {"weight": 0.05}, "Frankfurt": {"weight": 0.05}, "Lyon": {"weight": 0.04},
        "Manchester": {"weight": 0.05}, "Rotterdam": {"weight": 0.05},
    },
    "male_names": ["Thomas", "Alexander", "Maximilian", "Paul", "Jean", "Pierre", "Marco", "Luca", "Carlos", "Hugo", "Oliver", "William", "Jan", "Henrik", "Sebastian", "Felix", "Leon", "Noah", "Luis", "Emil"],
    "female_names": ["Maria", "Sophie", "Anna", "Emma", "Marie", "Charlotte", "Giulia", "Elena", "Laura", "Sara", "Julia", "Clara", "Lea", "Mia", "Isabella", "Amelia", "Elisa", "Chiara", "Lucia", "Hannah"],
    "last_names": ["Mueller", "Schmidt", "Schneider", "Fischer", "Martin", "Dubois", "Rossi", "Russo", "Ferrari", "Garcia", "Lopez", "Smith", "Taylor", "Wilson", "De Jong", "Van Dijk", "Jansen", "Meyer", "Bernard", "Wagner"],
    "occupations": {
        "Engineer": {"age_range": [24, 65], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.7, "income": ["Orta", "Orta-Yüksek", "Yüksek"]},
        "Teacher": {"age_range": [24, 65], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.35, "income": ["Orta-Düşük", "Orta"]},
        "Software Developer": {"age_range": [22, 55], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.72, "income": ["Orta-Yüksek", "Yüksek"]},
        "Marketing Manager": {"age_range": [26, 60], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.45, "income": ["Orta", "Orta-Yüksek"]},
        "Architect": {"age_range": [26, 65], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.5, "income": ["Orta", "Orta-Yüksek"]},
        "Consultant": {"age_range": [26, 65], "education": ["Yüksek Lisans", "Doktora"], "gender_ratio": 0.55, "income": ["Orta-Yüksek", "Yüksek"]},
        "Nurse": {"age_range": [22, 65], "education": ["Ön Lisans", "Üniversite"], "gender_ratio": 0.12, "income": ["Orta-Düşük", "Orta"]},
        "Chef": {"age_range": [20, 60], "education": ["Lise", "Ön Lisans"], "gender_ratio": 0.65, "income": ["Orta-Düşük", "Orta"]},
        "Sales Associate": {"age_range": [18, 55], "education": ["Lise", "Ön Lisans", "Üniversite"], "gender_ratio": 0.5, "income": ["Düşük", "Orta-Düşük"]},
        "Electrician": {"age_range": [20, 65], "education": ["Lise", "Ön Lisans"], "gender_ratio": 0.95, "income": ["Orta-Düşük", "Orta"]},
        "Professor": {"age_range": [35, 70], "education": ["Doktora"], "gender_ratio": 0.6, "income": ["Orta-Yüksek", "Yüksek"]},
        "Pharmacist": {"age_range": [26, 65], "education": ["Üniversite"], "gender_ratio": 0.4, "income": ["Orta", "Orta-Yüksek"]},
        "Lawyer": {"age_range": [27, 70], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.55, "income": ["Orta-Yüksek", "Yüksek"]},
        "Shop Assistant": {"age_range": [18, 50], "education": ["Ortaokul", "Lise"], "gender_ratio": 0.4, "income": ["Düşük", "Orta-Düşük"]},
        "Driver": {"age_range": [22, 65], "education": ["Ortaokul", "Lise"], "gender_ratio": 0.9, "income": ["Düşük", "Orta-Düşük"]},
        "Homemaker": {"age_range": [22, 75], "education": ["İlkokul", "Ortaokul", "Lise", "Ön Lisans", "Üniversite"], "gender_ratio": 0.0, "income": ["Düşük", "Orta-Düşük", "Orta"]},
        "Retired": {"age_range": [55, 80], "education": ["İlkokul", "Ortaokul", "Lise", "Ön Lisans", "Üniversite", "Yüksek Lisans", "Doktora"], "gender_ratio": 0.5, "income": ["Orta-Düşük", "Orta"]},
        "University Student": {"age_range": [18, 28], "education": ["Lise", "Ön Lisans", "Üniversite", "Yüksek Lisans"], "gender_ratio": 0.5, "income": ["Düşük"]},
    },
    "platforms_by_age": {"young": ["Instagram", "TikTok", "YouTube", "Snapchat"], "middle": ["Facebook", "Instagram", "LinkedIn", "YouTube"], "older": ["Facebook", "WhatsApp", "YouTube"]},
    "payment_preferences": {"Kredi Kartı": 0.35, "Banka Kartı": 0.30, "Dijital Cüzdan": 0.25, "Kapıda Ödeme": 0.10},
}
