"""Turkey demographics data."""

TURKEY_DEMOGRAPHICS = {
    "countries": ["Türkiye"],
    "cities": {
        "İstanbul": {"weight": 0.25, "country": "Türkiye"},
        "Ankara": {"weight": 0.12, "country": "Türkiye"},
        "İzmir": {"weight": 0.10, "country": "Türkiye"},
        "Bursa": {"weight": 0.07, "country": "Türkiye"},
        "Antalya": {"weight": 0.07, "country": "Türkiye"},
        "Adana": {"weight": 0.05, "country": "Türkiye"},
        "Konya": {"weight": 0.05, "country": "Türkiye"},
        "Gaziantep": {"weight": 0.05, "country": "Türkiye"},
        "Kayseri": {"weight": 0.04, "country": "Türkiye"},
        "Trabzon": {"weight": 0.04, "country": "Türkiye"},
        "Eskişehir": {"weight": 0.04, "country": "Türkiye"},
        "Samsun": {"weight": 0.04, "country": "Türkiye"},
        "Diyarbakır": {"weight": 0.04, "country": "Türkiye"},
        "Mersin": {"weight": 0.04, "country": "Türkiye"},
    },
    "male_names": ["Mehmet", "Mustafa", "Ahmet", "Ali", "Hüseyin", "Hasan", "İbrahim", "Ömer", "Murat", "Burak", "Emre", "Cem", "Kerem", "Yusuf", "Berk", "Kaan", "Can", "Arda", "Eren", "Onur"],
    "female_names": ["Fatma", "Ayşe", "Zeynep", "Emine", "Hatice", "Elif", "Merve", "Büşra", "Esra", "Selin", "Deniz", "İrem", "Ecrin", "Defne", "Ceren", "Gamze", "Pınar", "Derya", "Sibel", "Naz"],
    "last_names": ["Yılmaz", "Kaya", "Demir", "Çelik", "Şahin", "Yıldız", "Öztürk", "Aydın", "Özdemir", "Arslan", "Doğan", "Kılıç", "Aslan", "Erdoğan", "Korkmaz", "Çetin", "Koç", "Aksoy", "Polat", "Acar"],
    "occupations": {
        "Öğretmen": {"age_range": [24, 65], "education": ["Üniversite", "Yüksek Lisans", "Doktora"], "gender_ratio": 0.4, "income": ["Orta-Düşük", "Orta", "Orta-Yüksek"]},
        "Mühendis": {"age_range": [24, 65], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.7, "income": ["Orta", "Orta-Yüksek", "Yüksek"]},
        "Yazılımcı": {"age_range": [22, 55], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.75, "income": ["Orta", "Orta-Yüksek", "Yüksek"]},
        "Doktor": {"age_range": [28, 70], "education": ["Üniversite", "Yüksek Lisans", "Doktora"], "gender_ratio": 0.55, "income": ["Orta-Yüksek", "Yüksek"]},
        "Avukat": {"age_range": [26, 70], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.55, "income": ["Orta", "Orta-Yüksek", "Yüksek"]},
        "Eczacı": {"age_range": [26, 65], "education": ["Üniversite"], "gender_ratio": 0.4, "income": ["Orta-Yüksek", "Yüksek"]},
        "Mimar": {"age_range": [26, 65], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.5, "income": ["Orta", "Orta-Yüksek"]},
        "Bankacı": {"age_range": [24, 60], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.5, "income": ["Orta", "Orta-Yüksek"]},
        "Muhasebeci": {"age_range": [24, 65], "education": ["Ön Lisans", "Üniversite"], "gender_ratio": 0.5, "income": ["Orta-Düşük", "Orta"]},
        "Hemşire": {"age_range": [22, 60], "education": ["Ön Lisans", "Üniversite"], "gender_ratio": 0.15, "income": ["Orta-Düşük", "Orta"]},
        "Satış Danışmanı": {"age_range": [20, 55], "education": ["Lise", "Ön Lisans", "Üniversite"], "gender_ratio": 0.5, "income": ["Düşük", "Orta-Düşük", "Orta"]},
        "Esnaf": {"age_range": [25, 70], "education": ["İlkokul", "Ortaokul", "Lise", "Ön Lisans"], "gender_ratio": 0.85, "income": ["Orta-Düşük", "Orta", "Orta-Yüksek"]},
        "Teknisyen": {"age_range": [20, 60], "education": ["Lise", "Ön Lisans"], "gender_ratio": 0.9, "income": ["Orta-Düşük", "Orta"]},
        "Şoför": {"age_range": [25, 65], "education": ["İlkokul", "Ortaokul", "Lise"], "gender_ratio": 0.95, "income": ["Düşük", "Orta-Düşük"]},
        "Aşçı": {"age_range": [20, 60], "education": ["İlkokul", "Ortaokul", "Lise"], "gender_ratio": 0.6, "income": ["Düşük", "Orta-Düşük", "Orta"]},
        "Kuaför": {"age_range": [20, 55], "education": ["Ortaokul", "Lise"], "gender_ratio": 0.3, "income": ["Orta-Düşük", "Orta"]},
        "Çiftçi": {"age_range": [25, 75], "education": ["İlkokul", "Ortaokul"], "gender_ratio": 0.85, "income": ["Düşük", "Orta-Düşük"]},
        "İnşaat İşçisi": {"age_range": [20, 60], "education": ["İlkokul", "Ortaokul"], "gender_ratio": 0.98, "income": ["Düşük", "Orta-Düşük"]},
        "Garson": {"age_range": [18, 45], "education": ["İlkokul", "Ortaokul", "Lise"], "gender_ratio": 0.6, "income": ["Düşük", "Orta-Düşük"]},
        "Kurye": {"age_range": [20, 45], "education": ["Ortaokul", "Lise"], "gender_ratio": 0.9, "income": ["Düşük", "Orta-Düşük"]},
        "Polis Memuru": {"age_range": [22, 60], "education": ["Lise", "Ön Lisans", "Üniversite"], "gender_ratio": 0.85, "income": ["Orta-Düşük", "Orta"]},
        "Akademisyen": {"age_range": [30, 70], "education": ["Yüksek Lisans", "Doktora"], "gender_ratio": 0.55, "income": ["Orta", "Orta-Yüksek"]},
        "Yönetici": {"age_range": [30, 65], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.65, "income": ["Orta-Yüksek", "Yüksek"]},
        "Ev Hanımı": {"age_range": [22, 75], "education": ["İlkokul", "Ortaokul", "Lise", "Ön Lisans", "Üniversite"], "gender_ratio": 0.0, "income": ["Düşük", "Orta-Düşük", "Orta"]},
        "Emekli": {"age_range": [55, 80], "education": ["İlkokul", "Ortaokul", "Lise", "Ön Lisans", "Üniversite", "Yüksek Lisans", "Doktora"], "gender_ratio": 0.5, "income": ["Düşük", "Orta-Düşük", "Orta"]},
        "Üniversite Öğrencisi": {"age_range": [18, 28], "education": ["Lise", "Ön Lisans", "Üniversite", "Yüksek Lisans"], "gender_ratio": 0.5, "income": ["Düşük"]},
    },
    "platforms_by_age": {
        "young": ["Instagram", "TikTok", "YouTube", "Twitter"],
        "middle": ["Instagram", "Facebook", "YouTube", "Twitter"],
        "older": ["Facebook", "WhatsApp", "YouTube"],
    },
    "payment_preferences": {
        "Kredi Kartı": 0.40,
        "Banka Kartı": 0.25,
        "Kapıda Ödeme": 0.25,
        "Dijital Cüzdan": 0.10,
    },
}
