"""USA demographics data."""
USA_DEMOGRAPHICS = {
    "countries": ["United States"],
    "cities": {
        "New York": {"weight": 0.15}, "Los Angeles": {"weight": 0.12}, "Chicago": {"weight": 0.08},
        "Houston": {"weight": 0.07}, "Phoenix": {"weight": 0.05}, "San Francisco": {"weight": 0.06},
        "Seattle": {"weight": 0.05}, "Miami": {"weight": 0.06}, "Boston": {"weight": 0.05},
        "Austin": {"weight": 0.05}, "Denver": {"weight": 0.04}, "Atlanta": {"weight": 0.05},
        "Dallas": {"weight": 0.05}, "Portland": {"weight": 0.04}, "Nashville": {"weight": 0.04}, "San Diego": {"weight": 0.04},
    },
    "male_names": ["James", "John", "Robert", "Michael", "William", "David", "Joseph", "Thomas", "Charles", "Daniel", "Matthew", "Anthony", "Christopher", "Andrew", "Joshua", "Ryan", "Brandon", "Tyler", "Ethan", "Noah"],
    "female_names": ["Mary", "Jennifer", "Linda", "Elizabeth", "Sarah", "Jessica", "Emily", "Ashley", "Sophia", "Olivia", "Emma", "Ava", "Mia", "Isabella", "Charlotte", "Amelia", "Harper", "Abigail", "Ella", "Madison"],
    "last_names": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Anderson", "Taylor", "Thomas", "Moore", "Jackson", "Martin", "Lee", "Thompson", "White", "Harris"],
    "occupations": {
        "Software Engineer": {"age_range": [22, 60], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.72, "income": ["Orta-Yüksek", "Yüksek"]},
        "Teacher": {"age_range": [24, 65], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.3, "income": ["Orta-Düşük", "Orta"]},
        "Nurse (RN)": {"age_range": [23, 65], "education": ["Üniversite"], "gender_ratio": 0.12, "income": ["Orta", "Orta-Yüksek"]},
        "Marketing Manager": {"age_range": [26, 60], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.45, "income": ["Orta-Yüksek", "Yüksek"]},
        "Financial Analyst": {"age_range": [24, 60], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.6, "income": ["Orta-Yüksek", "Yüksek"]},
        "Attorney": {"age_range": [27, 70], "education": ["Yüksek Lisans"], "gender_ratio": 0.55, "income": ["Orta-Yüksek", "Yüksek"]},
        "Physician": {"age_range": [30, 70], "education": ["Doktora"], "gender_ratio": 0.55, "income": ["Yüksek"]},
        "Data Scientist": {"age_range": [24, 55], "education": ["Üniversite", "Yüksek Lisans", "Doktora"], "gender_ratio": 0.65, "income": ["Orta-Yüksek", "Yüksek"]},
        "Sales Associate": {"age_range": [18, 55], "education": ["Lise", "Ön Lisans", "Üniversite"], "gender_ratio": 0.5, "income": ["Düşük", "Orta-Düşük"]},
        "Electrician": {"age_range": [20, 65], "education": ["Lise", "Ön Lisans"], "gender_ratio": 0.95, "income": ["Orta-Düşük", "Orta"]},
        "Plumber": {"age_range": [20, 65], "education": ["Lise", "Ön Lisans"], "gender_ratio": 0.97, "income": ["Orta-Düşük", "Orta"]},
        "Barista": {"age_range": [18, 35], "education": ["Lise", "Ön Lisans"], "gender_ratio": 0.45, "income": ["Düşük"]},
        "Delivery Driver": {"age_range": [20, 60], "education": ["Ortaokul", "Lise"], "gender_ratio": 0.85, "income": ["Düşük", "Orta-Düşük"]},
        "Warehouse Worker": {"age_range": [18, 55], "education": ["Ortaokul", "Lise"], "gender_ratio": 0.75, "income": ["Düşük", "Orta-Düşük"]},
        "Accountant": {"age_range": [24, 65], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.5, "income": ["Orta", "Orta-Yüksek"]},
        "Product Manager": {"age_range": [26, 55], "education": ["Üniversite", "Yüksek Lisans"], "gender_ratio": 0.55, "income": ["Orta-Yüksek", "Yüksek"]},
        "Homemaker": {"age_range": [22, 75], "education": ["İlkokul", "Ortaokul", "Lise", "Ön Lisans", "Üniversite"], "gender_ratio": 0.0, "income": ["Düşük", "Orta-Düşük", "Orta"]},
        "Retired": {"age_range": [55, 80], "education": ["İlkokul", "Ortaokul", "Lise", "Ön Lisans", "Üniversite", "Yüksek Lisans", "Doktora"], "gender_ratio": 0.5, "income": ["Orta-Düşük", "Orta"]},
        "College Student": {"age_range": [18, 28], "education": ["Lise", "Ön Lisans", "Üniversite", "Yüksek Lisans"], "gender_ratio": 0.5, "income": ["Düşük"]},
    },
    "platforms_by_age": {"young": ["TikTok", "Instagram", "YouTube", "Snapchat"], "middle": ["Facebook", "Instagram", "LinkedIn", "YouTube"], "older": ["Facebook", "YouTube", "LinkedIn"]},
    "payment_preferences": {"Kredi Kartı": 0.45, "Banka Kartı": 0.25, "Dijital Cüzdan": 0.25, "Kapıda Ödeme": 0.05},
}
